# Generated by Django 4.1.2 on 2022-10-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Familia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='edad',
        ),
    ]
